Feature/52 animations
luscabap/sr-dente pull request #58
Opened 2024-08-24 17:33 UTC by luscabap

2024-08-24 21:46 UTC, Daniela-Alves2004 submitted a review, later dismissed

2024-08-26 10:23 UTC, Leonardo-Tozoni requested changes

2024-08-26 10:23 UTC, Leonardo-Tozoni commented on src/components/CardSobreMobile/index.tsx
> +      initial={{ x: primario ? -100 : 100 }}
Código deve ser padronizado em ingles

2024-08-26 10:23 UTC, Leonardo-Tozoni commented on src/components/ContainerIntroduction/index.tsx
> -        console.log('Botão clicado!');
Pode remover a função, se não tem tela não faz sentido executar uma função para o botão.

2024-08-26 10:23 UTC, Leonardo-Tozoni commented on src/components/MenuMobile/index.tsx
> +            {link.texto}
Padrão inglês

2024-08-26 13:18 UTC, Leonardo-Tozoni approved these changes

2024-08-26 13:18 UTC, merged